spring.application.name=backend

# ===============================
# DATABASE (Railway MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:40705/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hmbMZHexfZZKAuuaaVHTDauauWgBAgqN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER (Render requirement)
# ===============================
server.port=${PORT:8080}